# Generated by Django 3.2.9 on 2021-12-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=60)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('profile_img', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
